### ISSUE TITLE
Battery data not showing in BigSur

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/power#10]
The new script doesn't seem to collect the battery data. The client battery page appears blank and the relevant fields in the sql db are empty. I tried replacing it with the old sh script and while it partially works, it produces some nonsensical battery values - for example Battery Voltage Level	12883.00 Volts

Looking at the data file produced by v1.4 it seems ok so I'm not sure what the problem is, although at first glance it seems to miss the battery serial number maybe more.

EDIT: the powerinfo.plist  file produced on BigSur looks different.

**Comment by ofirgalcon** [comment]
I ran a few more tests and it appears the problem is with BigSur. I located the problem in the power script:

`if getOsVersion() < 8:`

Do we still need 10.7 compatibility? Since I'm a complete python idiot I tried solving the problem by replacing all the 8s with 0s, it didn't help. All I see in the battery page is the power adaptor info.

EDIT: This was wrong see next post

**Comment by ofirgalcon** [comment]
OK - so it wasn't `getOsVersion` since BigSur returns 10.16. The problem is both in the power script and in power_model.php - I can see the problems in the code, but I'm struggling to fix it all.

The problem is that Apple change the data structure here's the old result of `system_profiler SPPowerDataType -xml`
<img width="533" alt="image" src="https://user-images.githubusercontent.com/16665880/105935274-97c3c200-6049-11eb-850b-da70ccceb9be.png">
And this is the BigSur data
<img width="527" alt="image" src="https://user-images.githubusercontent.com/16665880/105935349-ba55db00-6049-11eb-85a1-5362b17b31ab.png">

**Comment by ofirgalcon** [comment]
So I made some progress, from displaying only the power adaptor
<img width="628" alt="image" src="https://user-images.githubusercontent.com/16665880/105951495-0748aa00-6068-11eb-8e7b-5a65ea0452e9.png">
Now displaying more data. Some of the data is obviously wrong but I'm making progress. I need help.
Manufactured (date) - Apple now encrypt this number as far as I can tell, need to hide it for BigSur
Full Charge Capacity - needs fixing, reported differently	
Health %	 - needs fixing, reported differently		
Charge Remaining	 - needs fixing, reported differently		
Charged % - needs fixing, reported differently			
etc...
<img width="626" alt="image" src="https://user-images.githubusercontent.com/16665880/105951603-3ced9300-6068-11eb-8c91-0bc710217eb4.png">

**Comment by ofirgalcon** [comment]
More progress: 

<img width="606" alt="image" src="https://user-images.githubusercontent.com/16665880/105967125-6bc23400-607d-11eb-9ec6-4e7aa399034f.png">

**Comment by tuxudo** [comment]
Should be fully resolved with the recent PRs
