### ISSUE TITLE
M1 MacBooks 

### ISSUE THREAD

**Issue by MarcelRei** [munkireport/power#15]
There seems to be an issue regarding the batteries of the M1 MacBooks.
It shows the right design capacity, but the capacity for all M1 MacBooks is listed as 100mah

**Comment by tuxudo** [comment]
Please test the as-fix branch located here to see if the issue is resolved https://github.com/munkireport/power/tree/as-fix

**Comment by MarcelRei** [comment]
That fixed it. Thanks

**Comment by tuxudo** [comment]
Thank you for the report. Still working on full support of AS Macs.
