### ISSUE TITLE
Feature request: display energy saver schedule

### ISSUE THREAD

**Issue by flammable** [munkireport/power#9]
Hey tuxudo!

Would it be possible to add the output of this command to the power module's listings?

`/usr/bin/pmset -g sched`

We use my [Boot Scheduler](https://github.com/flammable/boot_scheduler) project at work, and it'd be useful to be able to audit the scheduling settings on the Macs.

Thanks!

**Comment by tuxudo** [comment]
Done.

**Comment by flammable** [comment]
You are the best, thanks!
